---
- hosts: all
  tasks:
  - name: Copy nginx configuration file
    command: cp /vagrant/host-setup/dashServer/nginx.conf /usr/local/nginx/conf/
    become: yes

  - name: Start nginx webserver
    command: systemctl start nginx
    become: yes
    
  - name: Restart nginx webserver
    command: systemctl reload nginx
    become: yes